# Generated by Django 2.2.9 on 2020-04-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0002_auto_20200219_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='Abstract'),
        ),
    ]
