# Generated by Django 2.2.2 on 2019-09-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalresult',
            name='abstain',
        ),
        migrations.RemoveField(
            model_name='proposalresult',
            name='strong_accept',
        ),
        migrations.RemoveField(
            model_name='proposalresult',
            name='strong_reject',
        ),
        migrations.RemoveField(
            model_name='proposalresult',
            name='weak_accept',
        ),
        migrations.RemoveField(
            model_name='proposalresult',
            name='weak_reject',
        ),
        migrations.AddField(
            model_name='proposalresult',
            name='minus_one',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposalresult',
            name='minus_zero',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposalresult',
            name='plus_one',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposalresult',
            name='plus_zero',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='latestvote',
            name='vote',
            field=models.CharField(choices=[('+1', '+1 — Good proposal and I will argue for it to be accepted.'), ('+0', '+0 — OK proposal, but I will not argue for it to be accepted.'), ('−0', '−0 — Weak proposal, but I will not argue strongly against acceptance.'), ('−1', '−1 — Serious issues and I will argue to reject this proposal.')], max_length=2, verbose_name='Vote'),
        ),
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.CharField(blank=True, choices=[('+1', '+1 — Good proposal and I will argue for it to be accepted.'), ('+0', '+0 — OK proposal, but I will not argue for it to be accepted.'), ('−0', '−0 — Weak proposal, but I will not argue strongly against acceptance.'), ('−1', '−1 — Serious issues and I will argue to reject this proposal.')], max_length=2, verbose_name='Vote'),
        ),
    ]
