# Generated by Django 2.2.2 on 2019-10-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbase',
            name='description',
            field=models.TextField(blank=True, help_text='If your proposal is accepted this will be made public and printed in the program. Should be one paragraph, maximum 400 characters.', verbose_name='Brief Description'),
        ),
    ]
